# Generated by Django 4.1.3 on 2022-11-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cType', models.CharField(max_length=122)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('hour', models.IntegerField(null=True)),
                ('minute', models.IntegerField(null=True)),
                ('hundredBlock', models.CharField(max_length=122, null=True)),
                ('neighbourhood', models.CharField(max_length=122, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
